version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build and Export Next.js App
          command: |
            npm run build
            npm run export
      - run:
          name: Install AWS CLI
          command: sudo apt-get install -y awscli
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ./out s3://test-circleci-cikume --delete

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-deploy
